apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::552428235451:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-8R0JI6SXHRX7
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::552428235451:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-07-21T14:58:40Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "825"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 9cf7ea31-4227-49c5-adab-d54f8038186a
